services:
  traefik:
    image: traefik:v3.7
    container_name: traefik
    restart: unless-stopped
    
    security_opt:
      - no-new-privileges:true
    
    networks:
      - proxy
    
    ports:
      - "80:80"
      - "443:443"
    
    env_file:
      - .env
    
    volumes:
      - /etc/localtime:/etc/localtime:ro
      - /var/run/docker.sock:/var/run/docker.sock:ro
      - ./data/traefik.yml:/traefik.yml:ro
      - ./data/acme.json:/acme.json
      - ./data/config.yml:/config.yml:ro
    
    labels:
      - "traefik.enable=true"
      
      # Dashboard router
      - "traefik.http.routers.dashboard.rule=Host(`traefik.${DOMAIN}`)"
      - "traefik.http.routers.dashboard.entrypoints=websecure"
      - "traefik.http.routers.dashboard.service=api@internal"
      - "traefik.http.routers.dashboard.tls=true"
      - "traefik.http.routers.dashboard.tls.certresolver=cloudflare"

  cloudflared:
    image: cloudflare/cloudflared:latest
    container_name: cloudflared
    restart: unless-stopped
    
    command: tunnel --no-autoupdate run --token ${CLOUDFLARED_TOKEN}
    
    networks:
      - proxy
    
    depends_on:
      - traefik

networks:
  proxy:
    name: proxy
    driver: bridge
